// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzK5gMRpaE5_2Ng3vDPquEcePosUpBR0',
    appId: '1:702981099878:web:b1ff13e2930b0f2d3d78a7',
    messagingSenderId: '702981099878',
    projectId: 'unistayapp-95eac',
    authDomain: 'unistayapp-95eac.firebaseapp.com',
    storageBucket: 'unistayapp-95eac.firebasestorage.app',
    measurementId: 'G-GGQH740VW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn17BrFeD-tLzAD2pN6Qz7M014j8MsTBQ',
    appId: '1:702981099878:android:fef31586f97dbae13d78a7',
    messagingSenderId: '702981099878',
    projectId: 'unistayapp-95eac',
    storageBucket: 'unistayapp-95eac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfKjwRpO-YU6e5eINzGlCwEDyyVFiz-Yw',
    appId: '1:702981099878:ios:3851d894685b56363d78a7',
    messagingSenderId: '702981099878',
    projectId: 'unistayapp-95eac',
    storageBucket: 'unistayapp-95eac.firebasestorage.app',
    iosBundleId: 'com.example.unistayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfKjwRpO-YU6e5eINzGlCwEDyyVFiz-Yw',
    appId: '1:702981099878:ios:3851d894685b56363d78a7',
    messagingSenderId: '702981099878',
    projectId: 'unistayapp-95eac',
    storageBucket: 'unistayapp-95eac.firebasestorage.app',
    iosBundleId: 'com.example.unistayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQzK5gMRpaE5_2Ng3vDPquEcePosUpBR0',
    appId: '1:702981099878:web:100ee15a846834b93d78a7',
    messagingSenderId: '702981099878',
    projectId: 'unistayapp-95eac',
    authDomain: 'unistayapp-95eac.firebaseapp.com',
    storageBucket: 'unistayapp-95eac.firebasestorage.app',
    measurementId: 'G-MBG8HDVZ62',
  );
}
